---
- name: Stop Session/Service
  ansible.builtin.command: tmux kill-session

- name: Reboot VM
  ansible.builtin.reboot:
    reboot_timeout: 300
    
- name: Start Session/Service
  ansible.builtin.command: tmuxp load /home/ec2-user/maxheap.yaml 2>&1 > /home/ec2-user/aiops.log &
